site_name: FiveOrbs Log
copyright: © 2023 ebene fünf GmbH
nav:
  - index.md
theme:
    name: fiveorbs
repo_url: https://github.com/fiveorbs/log
extra:
  project: Log
plugins:
  - search
  - macros:
      module_name: docs/main
